THEMENAME	Fly Legacy Vector Window Theme
THEMEID	vect

WIDGET	VectorZoomIn
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorZoomIn.PBG

WIDGET	VectorZoomOut
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorZoomOut.PBG

WIDGET	VectorMaximize
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorMaximize.PBG

WIDGET	VectorRestore
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorRestore.PBG

WIDGET	VectorAirport
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorAirport.PBG

WIDGET	VectorVOR
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorVOR.PBG

WIDGET	VectorNDB
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorNDB.PBG

WIDGET	VectorCompass
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorCompass.PBG

WIDGET	VectorLabel
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorLabel.PBG

WIDGET	VectorGraphic
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorGraphic.PBG

WIDGET	VectorCursorInfo
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorCursorInfo.PBG

WIDGET	VectorOptions
	BITMAP	BACK		UI\Themes\Legacy\Vector\VectorOptions.PBG

WIDGET	VectorGroupbox
	COLOR	LINE		128 128 128
	COLOR	TEXT		255 255 255
	COLOR	BACK		  0   0   0

