THEMENAME	Fly Legacy Default UI Theme
THEMEID	defa

WIDGET	DefaultButton
	BITMAP	BACK		UI\Themes\Legacy\Buttons\SingleCenter.PBG
	BITMAP	LEFT		UI\Themes\Legacy\Buttons\SingleLeft.PBG
	BITMAP	RIGHT		UI\Themes\Legacy\Buttons\SingleRight.PBG
	COLOR	TEXT		0 0 0

WIDGET	Button
	BITMAP	BACK		UI\Themes\Legacy\Buttons\SingleCenter.PBG
	BITMAP	LEFT		UI\Themes\Legacy\Buttons\SingleLeft.PBG
	BITMAP	RIGHT		UI\Themes\Legacy\Buttons\SingleRight.PBG
	COLOR	TEXT		0 0 0

WIDGET	CheckBox
	BITMAP	BACK		UI\Themes\Legacy\Buttons\Checkbox.PBG

WIDGET	RadioButton
	BITMAP	BACK		UI\Themes\Legacy\Buttons\RadioButton.PBG

WIDGET	PopupMenu
	BITMAP	BACK		UI\Themes\Legacy\PopupMenus\Center.PBG
	BITMAP	LEFT		UI\Themes\Legacy\PopupMenus\Left.PBG
	BITMAP	RIGHT		UI\Themes\Legacy\PopupMenus\Right.PBG
	COLOR	TEXT		  0   0   0
	COLOR	SELECTION	255 255 255

WIDGET	MenuBar
	BITMAP	BACK		UI\Themes\Legacy\Menus\MainMenuBarCenter.PBM
	BITMAP	LEFT		UI\Themes\Legacy\Menus\MainMenuBarLeft.PBM
	BITMAP	RIGHT		UI\Themes\Legacy\Menus\MainMenuBarRight.PBM
	COLOR	TEXT		  0   0   0
	COLOR	HILITE		130 153 196
	COLOR	TEXTHILITE	  0   0   0

WIDGET	WindowMenuBar
	BITMAP	BACK		UI\Themes\Legacy\Menus\WindowMenuBarCenter.PBM
	BITMAP	LEFT		UI\Themes\Legacy\Menus\WindowMenuBarLeft.PBM
	BITMAP	RIGHT		UI\Themes\Legacy\Menus\WindowMenuBarRight.PBM
	COLOR	TEXT		255 255 255

WIDGET	Menu
	BITMAP	BACK		UI\Themes\Legacy\Menus\MenuBackground.PBM
	BITMAP	TOP		UI\Themes\Legacy\Menus\MenuTop.PBM
	BITMAP	BOTTOM	UI\Themes\Legacy\Menus\MenuBottom.PBM
	BITMAP	LEFT		UI\Themes\Legacy\Menus\MenuLeft.PBM
	BITMAP	RIGHT		UI\Themes\Legacy\Menus\MenuRight.PBM
	BITMAP	TOPLEFT	UI\Themes\Legacy\Menus\MenuTopLeft.PBM
	BITMAP	TOPRIGHT	UI\Themes\Legacy\Menus\MenuTopRight.PBM
	BITMAP	BOTLEFT	UI\Themes\Legacy\Menus\MenuBottomLeft.PBM
	BITMAP	BOTRIGHT	UI\Themes\Legacy\Menus\MenuBottomRight.PBM
	BITMAP	HILIGHT	UI\Themes\Legacy\Menus\MenuHilight.PBM
	COLOR	LINE		192 192 192
	COLOR	HILITE	130 153 196
	COLOR	TEXT		  0   0   0
	COLOR	TEXTHILITE	  0   0   0
	COLOR	TEXTGREY	128 128 128

WIDGET	Slider
	BITMAP	BACK		UI\Themes\Legacy\Sliders\HMiddle.PBG
	BITMAP	ALTBACK	UI\Themes\Legacy\Sliders\VMiddle.PBG
	BITMAP	HTHUMB	UI\Themes\Legacy\Sliders\HThumb.PBG
	BITMAP	VTHUMB	UI\Themes\Legacy\Sliders\VThumb.PBG
	BITMAP	HLTICK	UI\Themes\Legacy\Sliders\HTick.PBM
	BITMAP	HSTICK	UI\Themes\Legacy\Sliders\HTickSmall.PBM
	BITMAP	VLTICK	UI\Themes\Legacy\Sliders\VTick.PBM
	BITMAP	VSTICK	UI\Themes\Legacy\Sliders\VTickSmall.PBM

WIDGET	Scrollbar
	BITMAP	BACK		UI\Themes\Legacy\Scrollbars\HMiddle.PBG
	BITMAP	ALTBACK	UI\Themes\Legacy\Scrollbars\VMiddle.PBG
	BITMAP	LEFT		UI\Themes\Legacy\Scrollbars\ArrowLeft.PBG
	BITMAP	RIGHT		UI\Themes\Legacy\Scrollbars\ArrowRight.PBG
	BITMAP	TOP		UI\Themes\Legacy\Scrollbars\ArrowUp.PBG
	BITMAP	BOTTOM	UI\Themes\Legacy\Scrollbars\ArrowDown.PBG
	BITMAP	HTHUMB	UI\Themes\Legacy\Scrollbars\HThumb.PBG
	BITMAP	VTHUMB	UI\Themes\Legacy\Scrollbars\VThumb.PBG

WIDGET  Scrollbtn
	BITMAP  LEFT		UI\Themes\Legacy\Scrollbars\ArrowLeft.PBG
	BITMAP  RIGHT		UI\Themes\Legacy\Scrollbars\ArrowRight.PBG

WIDGET	List
	BITMAP	BACK		UI\Themes\Legacy\Lists\Background.PBM
	BITMAP	TOP		UI\Themes\Legacy\Lists\Top.PBM
	BITMAP	BOTTOM	UI\Themes\Legacy\Lists\Bottom.PBM
	BITMAP	LEFT		UI\Themes\Legacy\Lists\Left.PBM
	BITMAP	RIGHT		UI\Themes\Legacy\Lists\Right.PBM
	BITMAP	TOPLEFT	UI\Themes\Legacy\Lists\TopLeft.PBM
	BITMAP	TOPRIGHT	UI\Themes\Legacy\Lists\TopRight.PBM
	BITMAP	BOTLEFT	UI\Themes\Legacy\Lists\BottomLeft.PBM
	BITMAP	BOTRIGHT	UI\Themes\Legacy\Lists\BottomRight.PBM
	BITMAP	HILIGHT	UI\Themes\Legacy\Lists\Hilight.PBM
	COLOR	TEXT		  0   0   0
	COLOR	TEXTHILITE	255 255 255
	COLOR	HILITE	  0  97 142

WIDGET	Groupbox
	BITMAP	BACK		UI\Themes\Legacy\GroupBox\Background.PBM
	BITMAP	TOP		UI\Themes\Legacy\GroupBox\Top.PBM
	BITMAP	BOTTOM	UI\Themes\Legacy\GroupBox\Bottom.PBM
	BITMAP	LEFT		UI\Themes\Legacy\GroupBox\Left.PBM
	BITMAP	RIGHT		UI\Themes\Legacy\GroupBox\Right.PBM
	BITMAP	TOPLEFT	UI\Themes\Legacy\GroupBox\TopLeft.PBM
	BITMAP	TOPRIGHT	UI\Themes\Legacy\GroupBox\TopRight.PBM
	BITMAP	BOTLEFT	UI\Themes\Legacy\GroupBox\BottomLeft.PBM
	BITMAP	BOTRIGHT	UI\Themes\Legacy\GroupBox\BottomRight.PBM
	COLOR	LINE	 64  64  64
	COLOR	TEXT	  0   0   0

WIDGET	TextField
	BITMAP	BACK		UI\Themes\Legacy\TextFields\Background.PBM
	BITMAP	TOP		UI\Themes\Legacy\TextFields\Top.PBM
	BITMAP	BOTTOM	UI\Themes\Legacy\TextFields\Bottom.PBM
	BITMAP	LEFT		UI\Themes\Legacy\TextFields\Left.PBM
	BITMAP	RIGHT		UI\Themes\Legacy\TextFields\Right.PBM
	BITMAP	TOPLEFT	UI\Themes\Legacy\TextFields\TopLeft.PBM
	BITMAP	TOPRIGHT	UI\Themes\Legacy\TextFields\TopRight.PBM
	BITMAP	BOTLEFT	UI\Themes\Legacy\TextFields\BottomLeft.PBM
	BITMAP	BOTRIGHT	UI\Themes\Legacy\TextFields\BottomRight.PBM
	COLOR	TEXT		  0   0   0
	COLOR	HILITE	128   0 128
	COLOR	TEXTHILITE	255 255 255
	COLOR	LINE		  0   0   0
	COLOR	FILL		255 255 255
	COLOR	FILLDISABLED    128 128 128
	COLOR	CARET		  0   0   0

WIDGET	Picture
	BITMAP	BACK		UI\ICONS\samppic.pbm

WIDGET	Label
	COLOR	TEXT		  0   0   0
	COLOR	SHADOW	  0   0   0
		USESHADOW	  0

WIDGET	Line
	COLOR	LINE		0 0 0
	THICKNESS		1

WIDGET	Box
	BITMAP	BACK		UI\Themes\Legacy\Boxes\Background.PBM
	BITMAP	TOP		UI\Themes\Legacy\Boxes\Top.PBM
	BITMAP	BOTTOM	UI\Themes\Legacy\Boxes\Bottom.PBM
	BITMAP	LEFT		UI\Themes\Legacy\Boxes\Left.PBM
	BITMAP	RIGHT		UI\Themes\Legacy\Boxes\Right.PBM
	BITMAP	TOPLEFT	UI\Themes\Legacy\Boxes\TopLeft.PBM
	BITMAP	TOPRIGHT	UI\Themes\Legacy\Boxes\TopRight.PBM
	BITMAP	BOTLEFT	UI\Themes\Legacy\Boxes\BottomLeft.PBM
	BITMAP	BOTRIGHT	UI\Themes\Legacy\Boxes\BottomRight.PBM
	COLOR	LINE 0 0 0
	COLOR	FILL 0 0 0
	THICKNESS  1

WIDGET	Graph
	BITMAP	BACK		UI\Themes\Legacy\Boxes\Background.PBM
	BITMAP	TOP		UI\Themes\Legacy\Boxes\Top.PBM
	BITMAP	BOTTOM	UI\Themes\Legacy\Boxes\Bottom.PBM
	BITMAP	LEFT		UI\Themes\Legacy\Boxes\Left.PBM
	BITMAP	RIGHT		UI\Themes\Legacy\Boxes\Right.PBM
	BITMAP	TOPLEFT	UI\Themes\Legacy\Boxes\TopLeft.PBM
	BITMAP	TOPRIGHT	UI\Themes\Legacy\Boxes\TopRight.PBM
	BITMAP	BOTLEFT	UI\Themes\Legacy\Boxes\BottomLeft.PBM
	BITMAP	BOTRIGHT	UI\Themes\Legacy\Boxes\BottomRight.PBM
	COLOR	BACK		  0   0  32
	COLOR	LINE		128 128 128
	COLOR	TRACE		  0   0 255

WIDGET	Window
	BITMAP	BACK		UI\Themes\Legacy\Windows\Background.PBM
	BITMAP	TOP		UI\Themes\Legacy\Windows\Top.PBM
	BITMAP	BOTTOM	UI\Themes\Legacy\Windows\Bottom.PBM
	BITMAP	LEFT		UI\Themes\Legacy\Windows\Left.PBM
	BITMAP	RIGHT		UI\Themes\Legacy\Windows\Right.PBM
	BITMAP	TOPLEFT	UI\Themes\Legacy\Windows\TopLeft.PBM
	BITMAP	TOPRIGHT	UI\Themes\Legacy\Windows\TopRight.PBM
	BITMAP	BOTLEFT	UI\Themes\Legacy\Windows\BottomLeft.PBM
	BITMAP	BOTRIGHT	UI\Themes\Legacy\Windows\BottomRight.PBM

WIDGET	WindowTitle
	BITMAP	BACK		UI\Themes\Legacy\Windows\TitleCenter.PBG
	BITMAP	LEFT		UI\Themes\Legacy\Windows\TitleLeft.PBG
	BITMAP	RIGHT		UI\Themes\Legacy\Windows\TitleRight.PBG
	COLOR	TEXT		255 255 255

WIDGET	WindowCloseButton
	BITMAP	BACK		UI\Themes\Legacy\Windows\TitleClose.PBG

WIDGET	WindowMinimizeButton
	BITMAP	BACK		UI\Themes\Legacy\Windows\TitleMinimize.PBG

WIDGET	WindowZoomButton
	BITMAP	BACK		UI\Themes\Legacy\Windows\TitleZoom.PBG

WIDGET	RunwayCanvas
	BITMAP	TOP		UI\Themes\Legacy\Lists\Top.PBM
	BITMAP	BOTTOM	UI\Themes\Legacy\Lists\Bottom.PBM
	BITMAP	LEFT		UI\Themes\Legacy\Lists\Left.PBM
	BITMAP	RIGHT		UI\Themes\Legacy\Lists\Right.PBM
	BITMAP	TOPLEFT	UI\Themes\Legacy\Lists\TopLeft.PBM
	BITMAP	TOPRIGHT	UI\Themes\Legacy\Lists\TopRight.PBM
	BITMAP	BOTLEFT	UI\Themes\Legacy\Lists\BottomLeft.PBM
	BITMAP	BOTRIGHT	UI\Themes\Legacy\Lists\BottomRight.PBM
	COLOR	TEXT		  0   0   0
	COLOR	BACK		 64  64  64
